name: SonarCloud
run-name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout repositorio"
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f #v3: v3.4.0
        with:
          fetch-depth: 0
#     - name: "Install dependencies"
#       run: yarn
#     - name: "Test and coverage"
#       run: yarn jest --coverage
      - name: "SonarCloud Scan"
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=johnathanmb_juice-shop
            -Dsonar.organization=johnathanmb